name: Secret Diagnosis Check

on:
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    name: Check for required secrets
    steps:
      - name: Check if secrets are set
        run: |
          if [ -z "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" ]; then
            echo "❌ CLOUDFLARE_ACCOUNT_ID is NOT SET"
          else
            echo "✅ CLOUDFLARE_ACCOUNT_ID is SET"
          fi
          if [ -z "${{ secrets.CLOUDFLARE_API_TOKEN }}" ]; then
            echo "❌ CLOUDFLARE_API_TOKEN is NOT SET"
          else
            echo "✅ CLOUDFLARE_API_TOKEN is SET"
          fi
          if [ -z "${{ secrets.GH_TOKEN }}" ]; then
            echo "❌ GH_TOKEN is NOT SET"
          else
            echo "✅ GH_TOKEN is SET"
          fi
